// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package data

type IntSuccess struct {
	valueint int
}

func (r *IntSuccess) ErrorInfo() string {
	return ""
}

func (r *IntSuccess) IsOK() bool {
	return true
}
func (r *IntSuccess) Errors() []string {
	return []string{}
}
func NewIntSuccess(a int) *IntSuccess {
	return &IntSuccess{a}
}
func (r *IntSuccess) GetInt() int {
	return r.valueint
}
