// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package data

type StringSuccess struct {
	valuestring string
}

func (r *StringSuccess) ErrorInfo() string {
	return ""
}

func (r *StringSuccess) IsOK() bool {
	return true
}
func (r *StringSuccess) Errors() []string {
	return []string{}
}
func NewStringSuccess(a string) *StringSuccess {
	return &StringSuccess{a}
}
func (r *StringSuccess) GetString() string {
	return r.valuestring
}
